version: 0.2
run-as: ubuntu

batch:
  fast-fail: false
  build-list:
    - identifier: identity_database
      ignore-failure: false
      buildspec: identity-database/buildspec.yml

    - identifier: identity_service
      ignore-failure: false
      buildspec: identity-service/buildspec.yml

    - identifier: task_database
      ignore-failure: false
      buildspec: task-database/buildspec.yml

    - identifier: task_service
      ignore-failure: false
      buildspec: task-service/buildspec.yml

    - identifier: user_web
      ignore-failure: false
      buildspec: user-web/buildspec.yml

artifacts:
  files:
    - build/build.json
  name: batch-build
  secondary-artifacts:
    identity_database:
      files:
        - 'identity-database/**/*'
      name: identity_database-artifact
    identity_service:
      files:
        - 'identity-service/**/*'
      name: identity_service-artifact
    task_database:
      files:
        - 'task-database/**/*'
      name: task_database-artifact
    task_service:
      files:
        - 'task-service/**/*'
      name: task_service-artifact
    user_web:
      files:
        - 'user-web/**/*'
      name: user_web-artifact