apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-database
  labels:
    app.kubernetes.io/name: app-id-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-id-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-id-db
    spec:
      containers:
        - name: identity-database
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: letmein12345
            - name: MYSQL_DATABASE
              value: TaskManagerIdentity
