apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-database
  labels:
    app.kubernetes.io/name: app-task-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-task-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-task-db
    spec:
      containers:
        - name: task-database
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: root
            - name: MONGODB_INITDB_ROOT_PASSWORD
              value: letmein12345
            - name: MYSQL_DATABASE
              value: MONGODB_DATABASE
