apiVersion: v1
kind: Service
metadata:
  name: ui-web
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
