# Stage 1: Build the React app
FROM node:20.18.0-alpine3.20 as build
WORKDIR /root/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Copy built React app from the previous stage
COPY --from=build /root/app/dist /var/www/task-manager-user

# Copy Nginx config template
COPY ./default.conf /etc/nginx/conf.d/default.conf