name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  EKS_CLUSTER_NAME: eks-cicd-cluster

jobs:
  prepare_tag:
    outputs:
      tag: ${{ steps.semver.outputs.next }}
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Defaults to patch version, will bump minor on "feat" commit

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          fallbackTag: v0.0.1

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""

  build_and_push:
    permissions:
      contents: write
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: prepare_tag

    strategy:
      matrix:
        include:
          - image: ecr-repo-id-db
            dockerfile: identity-database/Dockerfile
            path: identity-database
            kubedeployment: _kubernetes/deployments/kube-deployment-id-database.yaml
          - image: ecr-repo-id-svc
            dockerfile: identity-service/Dockerfile
            path: identity-service
            kubedeployment: _kubernetes/deployments/kube-deployment-id.yaml
          - image: ecr-repo-ta-db
            dockerfile: task-database/Dockerfile
            path: task-database
            kubedeployment: _kubernetes/deployments/kube-deployment-task-database.yaml
          - image: ecr-repo-ta-svc
            dockerfile: task-service/Dockerfile
            path: task-service
            kubedeployment: _kubernetes/deployments/kube-deployment-task.yaml
          - image: ecr-repo-wb-ui
            dockerfile: user-web/Dockerfile
            path: user-web
            kubedeployment: _kubernetes/deployments/kube-deployment-web.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Assuming AWS IAM Role
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-ECR-kirazero1x
          role-session-name: GitHub_Role_AWS_OIDC_ssn
          aws-region: ${{ env.AWS_REGION }}

      - name: Check my role with Sts Get Caller Identity
        run: |
          aws sts get-caller-identity 
      
      - name: Login to Amazon Elastic Container Registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.image }}
          IMAGE_TAG: ${{ needs.prepare_tag.outputs.tag }}
          BUILD_PATH: ${{ matrix.path }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest $BUILD_PATH
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
  
      - name: Replace the images in the manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.image }}
          IMAGE_TAG: ${{ needs.prepare_tag.outputs.tag }}
        run: |
          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" ${{ matrix.kubedeployment }}
      
      - name: Deploy to EKS
        env:
          NAMESPACE: eks-cicd-apps
          KUBECONFIG: "/home/runner/.kube/config"
        run: |
          ls $KUBECONFIG
          kubectl create namespace $NAMESPACE || echo "namespace already exists"
          kubectl apply -f _kubernetes/deployments -n $NAMESPACE
          kubectl apply -f _kubernetes/services -n $NAMESPACE
          kubectl apply -f _kubernetes/kube-svc-web.yaml -n $NAMESPACE